# Generated by Django 3.1.3 on 2020-11-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='poster',
            options={'verbose_name': 'Poster', 'verbose_name_plural': 'Posters'},
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default='Family', max_length=200),
        ),
    ]
