# Generated by Django 3.1.3 on 2020-11-12 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='movie_name',
        ),
        migrations.AddField(
            model_name='poster',
            name='movie_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='movie_id', to='movies.movie'),
        ),
    ]
