# Generated by Django 3.1.3 on 2020-11-12 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20201112_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_id', to='movies.movie'),
        ),
    ]
